library(FishPhyloMaker)
comm <- read.table("~/OneDrive/Manuscritos/MS_FishPhyloMaker/data/comm2.txt", header = TRUE)
taxon_data <- FishTaxaMaker(comm)
Loricariidae
Siluriformes
Anostomidae
Characiformes
Serrasalmidae
Characiformes
Auchenipteridae
Siluriformes
Auchenipteridae
Siluriformes
Auchenipteridae
Siluriformes

res_phylo <- FishPhyloMaker(data = taxon_data, return.insertions = TRUE)
Catoprion
Delturus
Anostomus
Glanidium
Delturus
Ctenolucius
Amazonspinther
Bivibranchia
Gymnotus
Harttia
Leporinus
Cteniloricaria
Harttiella
Schizodon
Leporinus
Rhamdia
Pareiorhina
Leporinus
Hemiodus
Plagioscion
Plagioscion
Acanthopoma
Otolithes
Anostomus
Gymnotus
Apomatoceros
Ilisha
Pimelabditus
Acnodon
Schizodon
Epapterus
Hisonotus
Ancistrus
Loricaria
Pseudanos
Anostomus
Dekeyseria
Loricariidae
Hypopomidae
Apteronotidae
Apteronotidae
Characidae
Leporinus
Monopterus
Tatia
Trachycorystes
Epapterus
Auchenipteridae
table(res_phylo$Insertions_data$insertions)
res_phylo$Insertions_data[which(res_phylo$Insertions_data$insertions == "Not_inserted"), ]
